### ISSUE TITLE
Bug #2 - Profile Page Issue

### ISSUE THREAD

**Issue by Shubhamgupta-97** [WebGemTech/E-Learning#4]
I have an issue with the profile page - The CSS file is not working, I have tried to find out the issue but failed to resolve it.
![Screenshot (567)](https://github.com/WebGemTech/E-Learning/assets/101589523/1749cd09-b832-407a-8e33-cc6b2ee8e4c0)

**Comment by pratikmoredev** [comment]
Step 1: Login and Click on Profile.
Step 2: Right Click on the page and go to inspect elements.
Step 3: Go to Network Tab in Inspect Elements then again click refresh
Step 4: All the red files are not fetched from the code
Step 5: [ THE PROBLEM ]: All these files' path is not found.
Step 6: Click on each red file and check the Request URL if the image or file is not found on this path then it will generate an error 404.

Solution: 

1st Solution) Copy and paste the file on the path. **_NOTE: This will duplicate the files but for this project, it's okay it is due to the versions that the instructor is using._** 

2nd Solution) Check the Routing structure, you will need to create a route by your own logic and take references from youtube, google while creating the route file I have a pattern if you need that but I prefer you both can find solution.

Both options are good and working. It depends on you what you and Shruti will choose. The second Solution is very tricky I can explain to you why. So, you can go ahead with 1st for this project as it will take time to find a solution and We need to work on the client project as well! Also, try to complete it by the 31st of July after that we will take 2 months for our client project.

Let me know if you need anything else..
